import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SpessasynthProvider } from "./context/spessasynth-context";
import AllowSound from "@/components/tools/allow-sound";
import { RemoteProvider } from "./context/remote-context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AllowSound>
        <RemoteProvider>
          <SpessasynthProvider>
            <body className={inter.className}>{children}</body>
          </SpessasynthProvider>
        </RemoteProvider>
      </AllowSound>
    </html>
  );
}
