export const WALLPAPER = "wallpaper-3.png";
export const DEFAULT_SOUND_FONT = "default-sound-font.sf2";
export const MID_FILE_TYPE = "mid";
export const CUR_FILE_TYPE = "cur";
export const LYR_FILE_TYPE = "lyr";
export const EMK_FILE_TYPE = "emk";

export const STORAGE_NAME = "Song";
export const STORAGE_SOUNDFONT = "soundfont";
export const STORAGE_NAME_DIC = "song_dic";
export const STORAGE_SOUNDFONT_DIC = "soundfont_dic";
export const TRACKLIST_FILENAME = "song.json";

export const EMK_TYPE = "EMK";
export const NCN_TYPE = "NCN";
export const SONG_TYPE = { 0: EMK_TYPE, 1: NCN_TYPE };

export const INSTRUMENTS: { [key: number]: IInstruments | undefined } = {
  0: { name: "Acoustic Grand Piano", icon: "MdPiano" },
  1: { name: "Bright Acoustic Piano", icon: "MdPiano" },
  2: { name: "Electric Grand Piano", icon: "MdPiano" },
  3: { name: "Honky-tonk Piano", icon: "MdPiano" },
  4: { name: "Electric Piano 1", icon: "MdPiano" },
  5: { name: "Electric Piano 2", icon: "MdPiano" },
  6: { name: "Harpsichord", icon: "FaGuitar" },
  7: { name: "Clavinet", icon: "FaGuitar" },
  8: { name: "Celesta", icon: "FaBell" },
  9: { name: "Glockenspiel", icon: "FaBell" },
  10: { name: "Music Box", icon: "FaMusic" },
  11: { name: "Vibraphone", icon: "FaMusic" },
  12: { name: "Marimba", icon: "FaMusic" },
  13: { name: "Xylophone", icon: "FaMusic" },
  14: { name: "Tubular Bells", icon: "FaBell" },
  15: { name: "Dulcimer", icon: "FaMusic" },
  16: { name: "Drawbar Organ", icon: "FaChurch" },
  17: { name: "Percussive Organ", icon: "FaChurch" },
  18: { name: "Rock Organ", icon: "FaChurch" },
  19: { name: "Church Organ", icon: "FaChurch" },
  20: { name: "Reed Organ", icon: "FaChurch" },
  21: { name: "Accordion", icon: "FaMusic" },
  22: { name: "Harmonica", icon: undefined },
  23: { name: "Tango Accordion", icon: "FaMusic" },
  24: { name: "Acoustic Guitar (nylon)", icon: "FaGuitar" },
  25: { name: "Acoustic Guitar (steel)", icon: "FaGuitar" },
  26: { name: "Electric Guitar (jazz)", icon: "FaGuitar" },
  27: { name: "Electric Guitar (clean)", icon: "FaGuitar" },
  28: { name: "Electric Guitar (muted)", icon: "FaGuitar" },
  29: { name: "Overdriven Guitar", icon: "FaGuitar" },
  30: { name: "Distortion Guitar", icon: "FaGuitar" },
  31: { name: "Guitar harmonics", icon: "FaGuitar" },
  32: { name: "Acoustic Bass", icon: undefined },
  33: { name: "Electric Bass (finger)", icon: undefined },
  34: { name: "Electric Bass (pick)", icon: undefined },
  35: { name: "Fretless Bass", icon: undefined },
  36: { name: "Slap Bass 1", icon: undefined },
  37: { name: "Slap Bass 2", icon: undefined },
  38: { name: "Synth Bass 1", icon: "FaKeyboard" },
  39: { name: "Synth Bass 2", icon: "FaKeyboard" },
  40: { name: "Violin", icon: undefined },
  41: { name: "Viola", icon: undefined },
  42: { name: "Cello", icon: undefined },
  43: { name: "Contrabass", icon: undefined },
  44: { name: "Tremolo Strings", icon: undefined },
  45: { name: "Pizzicato Strings", icon: undefined },
  46: { name: "Orchestral Harp", icon: "FaMusic" },
  47: { name: "Timpani", icon: "FaDrum" },
  48: { name: "String Ensemble 1", icon: "FaMusic" },
  49: { name: "String Ensemble 2", icon: "FaMusic" },
  50: { name: "SynthStrings 1", icon: "FaKeyboard" },
  51: { name: "SynthStrings 2", icon: "FaKeyboard" },
  52: { name: "Choir Aahs", icon: "FaUsers" },
  53: { name: "Voice Oohs", icon: "FaUsers" },
  54: { name: "Synth Voice", icon: "FaMicrophone" },
  55: { name: "Orchestra Hit", icon: "FaMusic" },
  56: { name: "Trumpet", icon: undefined },
  57: { name: "Trombone", icon: undefined },
  58: { name: "Tuba", icon: undefined },
  59: { name: "Muted Trumpet", icon: undefined },
  60: { name: "French Horn", icon: undefined },
  61: { name: "Brass Section", icon: "FaUsers" },
  62: { name: "SynthBrass 1", icon: "FaKeyboard" },
  63: { name: "SynthBrass 2", icon: "FaKeyboard" },
  64: { name: "Soprano Sax", icon: undefined },
  65: { name: "Alto Sax", icon: undefined },
  66: { name: "Tenor Sax", icon: undefined },
  67: { name: "Baritone Sax", icon: undefined },
  68: { name: "Oboe", icon: "FaMusic" },
  69: { name: "English Horn", icon: "FaMusic" },
  70: { name: "Bassoon", icon: "FaMusic" },
  71: { name: "Clarinet", icon: "FaMusic" },
  72: { name: "Piccolo", icon: "FaMusic" },
  73: { name: "Flute", icon: "FaMusic" },
  74: { name: "Recorder", icon: "FaMusic" },
  75: { name: "Pan Flute", icon: "FaMusic" },
  76: { name: "Blown Bottle", icon: "FaMusic" },
  77: { name: "Shakuhachi", icon: "FaMusic" },
  78: { name: "Whistle", icon: "FaMusic" },
  79: { name: "Ocarina", icon: "FaMusic" },
  80: { name: "Lead 1 (square)", icon: "FaMicrophone" },
  81: { name: "Lead 2 (sawtooth)", icon: "FaMicrophone" },
  82: { name: "Lead 3 (calliope)", icon: "FaMicrophone" },
  83: { name: "Lead 4 (chiffer)", icon: "FaMicrophone" },
  84: { name: "Lead 5 (charang)", icon: "FaMicrophone" },
  85: { name: "Lead 6 (voice)", icon: "FaMicrophone" },
  86: { name: "Lead 7 (fifths)", icon: "FaMicrophone" },
  87: { name: "Lead 8 (bass + lead)", icon: "FaMicrophone" },
  88: { name: "Pad 1 (new age)", icon: "FaMusic" },
  89: { name: "Pad 2 (warm)", icon: "FaMusic" },
  90: { name: "Pad 3 (polysynth)", icon: "FaMusic" },
  91: { name: "Pad 4 (choir)", icon: "FaMusic" },
  92: { name: "Pad 5 (bowed)", icon: "FaMusic" },
  93: { name: "Pad 6 (metallic)", icon: "FaMusic" },
  94: { name: "Pad 7 (halo)", icon: "FaMusic" },
  95: { name: "Pad 8 (sweep)", icon: "FaMusic" },
  96: { name: "FX 1 (rain)", icon: "FaCloudRain" },
  97: { name: "FX 2 (soundtrack)", icon: "FaMusic" },
  98: { name: "FX 3 (crystal)", icon: "FaGem" },
  99: { name: "FX 4 (atmosphere)", icon: "FaCloud" },
  100: { name: "FX 5 (brightness)", icon: "FaSun" },
  101: { name: "FX 6 (goblins)", icon: "FaGhost" },
  102: { name: "FX 7 (echoes)", icon: undefined },
  103: { name: "FX 8 (sci-fi)", icon: "FaRobot" },
  104: { name: "Sitar", icon: "FaGuitar" },
  105: { name: "Banjo", icon: "FaGuitar" },
  106: { name: "Shamisen", icon: "FaGuitar" },
  107: { name: "Koto", icon: "FaGuitar" },
  108: { name: "Kalimba", icon: "FaMusic" },
  109: { name: "Bagpipe", icon: "FaMusic" },
  110: { name: "Fiddle", icon: undefined },
  111: { name: "Shanai", icon: "FaMusic" },
  112: { name: "Tinkle Bell", icon: "FaBell" },
  113: { name: "Agogo", icon: "FaMusic" },
  114: { name: "Steel Drums", icon: "FaDrumSteelpan" },
  115: { name: "Woodblock", icon: "FaMusic" },
  116: { name: "Taiko Drum", icon: "FaDrum" },
  117: { name: "Melodic Tom", icon: "FaDrum" },
  118: { name: "Synth Drum", icon: "FaDrum" },
  119: { name: "Reverse Cymbal", icon: "FaDrum" },
  120: { name: "Guitar Fret Noise", icon: "FaGuitar" },
  121: { name: "Breath Noise", icon: "FaWind" },
  122: { name: "Seashore", icon: "FaWater" },
  123: { name: "Bird Tweet", icon: "FaDove" },
  124: { name: "Telephone Ring", icon: "FaPhone" },
  125: { name: "Helicopter", icon: "FaHelicopter" },
  126: { name: "Applause", icon: "FaHandsClapping" },
  127: { name: "Gunshot", icon: "FaBomb" },
};
