export const instrumentNameToChannelMapping: any = {
  //   accordion: 22,
  acoustic_bass: 33,
  acoustic_grand_piano: 1,
  //   acoustic_guitar_nylon: 25,
  acoustic_guitar_steel: 26,
  //   agogo: 114,
  //   alto_sax: 66,
  //   applause: 127,
  //   bagpipe: 110,
  //   banjo: 106,
  //   baritone_sax: 68,
  //   bassoon: 71,
  //   bird_tweet: 124,
  //   blown_bottle: 77,
  //   brass_section: 62,
  //   breath_noise: 122,
  //   bright_acoustic_piano: 2,
  //   celesta: 9,
  //   cello: 43,
  //   choir_aahs: 53,
  //   church_organ: 20,
  //   clarinet: 72,
  //   clavinet: 8,
  //   contrabass: 44,
  //   distortion_guitar: 31,
  //   drawbar_organ: 17,
  //   dulcimer: 16,
  //   electric_bass_finger: 34,
  //   electric_bass_pick: 35,
  //   electric_grand_piano: 3,
  //   electric_guitar_clean: 28,
  //   electric_guitar_jazz: 27,
  //   electric_guitar_muted: 29,
  //   electric_piano_1: 5,
  //   electric_piano_2: 6,
  //   english_horn: 70,
  //   fiddle: 111,
  //   flute: 74,
  //   french_horn: 61,
  //   fretless_bass: 36,
  //   fx_1_rain: 97,
  //   fx_2_soundtrack: 98,
  //   fx_3_crystal: 99,
  //   fx_4_atmosphere: 100,
  //   fx_5_brightness: 101,
  //   fx_6_goblins: 102,
  //   fx_7_echoes: 102,
  //   fx_8_scifi: 104,
  //   glockenspiel: 10,
  //   guitar_fret_noise: 121,
  //   guitar_harmonics: 32,
  //   gunshot: 128,
  //   harmonica: 23,
  //   harpsichord: 7,
  //   helicopter: 126,
  //   honkytonk_piano: 4,
  //   kalimba: 109,
  //   koto: 108,
  //   lead_1_square: 81,
  //   lead_2_sawtooth: 82,
  //   lead_3_calliope: 83,
  //   lead_4_chiff: 84,
  //   lead_5_charang: 85,
  //   lead_6_voice: 86,
  //   lead_7_fifths: 87,
  //   lead_8_bass__lead: 88,
  //   marimba: 13,
  //   melodic_tom: 118,
  //   music_box: 11,
  //   muted_trumpet: 60,
  //   oboe: 69,
  //   ocarina: 80,
  //   orchestra_hit: 56,
  //   orchestral_harp: 47,
  //   overdriven_guitar: 30,
  //   pad_1_new_age: 89,
  //   pad_2_warm: 90,
  //   pad_3_polysynth: 91,
  //   pad_4_choir: 92,
  //   pad_5_bowed: 93,
  //   pad_6_metallic: 94,
  //   pad_7_halo: 95,
  //   pad_8_sweep: 96,
  //   pan_flute: 76,
  //   percussive_organ: 18,
  //   piccolo: 73,
  //   pizzicato_strings: 46,
  //   recorder: 75,
  //   reed_organ: 21,
  //   reverse_cymbal: 120,
  //   rock_organ: 19,
  //   seashore: 123,
  //   shakuhachi: 78,
  //   shamisen: 107,
  //   shanai: 112,
  //   sitar: 105,
  //   slap_bass_1: 37,
  //   slap_bass_2: 38,
  //   soprano_sax: 65,
  //   steel_drums: 115,
  //   string_ensemble_1: 49,
  //   string_ensemble_2: 50,
  //   synth_bass_1: 39,
  //   synth_bass_2: 40,
  //   synth_brass_1: 63,
  //   synth_brass_2: 64,
  //   synth_choir: 92,
  //   synth_drum: 119,
  //   synth_strings_1: 51,
  //   synth_strings_2: 52,
  //   taiko_drum: 117,
  //   tango_accordion: 24,
  //   telephone_ring: 125,
  //   tenor_sax: 67,
  //   timpani: 48,
  //   tinkle_bell: 113,
  //   tremolo_strings: 45,
  //   trombone: 58,
  //   trumpet: 57,
  //   tuba: 59,
  //   tubular_bells: 15,
  //   vibraphone: 12,
  //   viola: 42,
  violin: 41,
  //   voice_oohs: 54,
  //   whistle: 79,
  //   woodblock: 116,
    xylophone: 14,
};

export const instrumentChannel: any = {
  1: "acoustic_grand_piano",
  2: "acoustic_bass",
  3: "acoustic_grand_piano",
  4: "acoustic_grand_piano",
  5: "acoustic_guitar_steel",
  6: "violin",
  7: "acoustic_grand_piano",
  8: "xylophone",
  9: "acoustic_grand_piano",
  //   22: "accordion",
  //   33: "acoustic_bass",
  //   25: "acoustic_guitar_nylon",
  //   26: "acoustic_guitar_steel",
  //   114: "agogo",
  //   66: "alto_sax",
  //   127: "applause",
  //   110: "bagpipe",
  //   106: "banjo",
  //   68: "baritone_sax",
  //   71: "bassoon",
  //   124: "bird_tweet",
  //   77: "blown_bottle",
  //   62: "brass_section",
  //   122: "breath_noise",
  //   2: "bright_acoustic_piano",
  //   9: "celesta",
  //   43: "cello",
  //   53: "choir_aahs",
  //   20: "church_organ",
  //   72: "clarinet",
  //   8: "clavinet",
  //   44: "contrabass",
  //   31: "distortion_guitar",
  //   17: "drawbar_organ",
  //   16: "dulcimer",
  //   34: "electric_bass_finger",
  //   35: "electric_bass_pick",
  //   3: "electric_grand_piano",
  //   28: "electric_guitar_clean",
  //   27: "electric_guitar_jazz",
  //   29: "electric_guitar_muted",
  //   5: "electric_piano_1",
  //   6: "electric_piano_2",
  //   70: "english_horn",
  //   111: "fiddle",
  //   74: "flute",
  //   61: "french_horn",
  //   36: "fretless_bass",
  //   97: "fx_1_rain",
  //   98: "fx_2_soundtrack",
  //   99: "fx_3_crystal",
  //   100: "fx_4_atmosphere",
  //   101: "fx_5_brightness",
  //   102: "fx_6_goblins",
  //   103: "fx_7_echoes",
  //   104: "fx_8_scifi",
  //   10: "glockenspiel",
  //   121: "guitar_fret_noise",
  //   32: "guitar_harmonics",
  //   128: "gunshot",
  //   23: "harmonica",
  //   7: "harpsichord",
  //   126: "helicopter",
  //   4: "honkytonk_piano",
  //   109: "kalimba",
  //   108: "koto",
  //   81: "lead_1_square",
  //   82: "lead_2_sawtooth",
  //   83: "lead_3_calliope",
  //   84: "lead_4_chiff",
  //   85: "lead_5_charang",
  //   86: "lead_6_voice",
  //   87: "lead_7_fifths",
  //   88: "lead_8_bass__lead",
  //   13: "marimba",
  //   118: "melodic_tom",
  //   11: "music_box",
  //   60: "muted_trumpet",
  //   69: "oboe",
  //   80: "ocarina",
  //   56: "orchestra_hit",
  //   47: "orchestral_harp",
  //   30: "overdriven_guitar",
  //   89: "pad_1_new_age",
  //   90: "pad_2_warm",
  //   91: "pad_3_polysynth",
  //   92: "pad_4_choir",
  //   93: "pad_5_bowed",
  //   94: "pad_6_metallic",
  //   95: "pad_7_halo",
  //   96: "pad_8_sweep",
  //   76: "pan_flute",
  //   18: "percussive_organ",
  //   73: "piccolo",
  //   46: "pizzicato_strings",
  //   75: "recorder",
  //   21: "reed_organ",
  //   120: "reverse_cymbal",
  //   19: "rock_organ",
  //   123: "seashore",
  //   78: "shakuhachi",
  //   107: "shamisen",
  //   112: "shanai",
  //   105: "sitar",
  //   37: "slap_bass_1",
  //   38: "slap_bass_2",
  //   65: "soprano_sax",
  //   115: "steel_drums",
  //   49: "string_ensemble_1",
  //   50: "string_ensemble_2",
  //   39: "synth_bass_1",
  //   40: "synth_bass_2",
  //   63: "synth_brass_1",
  //   64: "synth_brass_2",
  //   //   93: "synth_choir",
  //   119: "synth_drum",
  //   51: "synth_strings_1",
  //   52: "synth_strings_2",
  //   117: "taiko_drum",
  //   24: "tango_accordion",
  //   125: "telephone_ring",
  //   67: "tenor_sax",
  //   48: "timpani",
  //   113: "tinkle_bell",
  //   45: "tremolo_strings",
  //   58: "trombone",
  //   57: "trumpet",
  //   59: "tuba",
  //   15: "tubular_bells",
  //   12: "vibraphone",
  //   42: "viola",
  //   41: "violin",
  //   54: "voice_oohs",
  //   79: "whistle",
  //   116: "woodblock",
  //   14: "xylophone",
};

const instrumentChannelToNameMapping: any = Object.keys(
  instrumentNameToChannelMapping
).reduce((acc, instrumentName) => {
  const instrumentChannel = instrumentNameToChannelMapping[instrumentName];
  return Object.assign({}, acc, {
    [instrumentChannel]: instrumentName,
  });
}, {});

export const getInstrumentName = (channel: any) => {
  if (channel === 0) return instrumentChannelToNameMapping[1];
  return instrumentChannelToNameMapping[channel];
};
