import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { SpessasynthProvider } from "../../context/spessasynth-context";
import AllowSound from "@/components/tools/allow-sound";

import { PeerProvider } from "../../context/remote-context";
import { AppControlProvider } from "@/context/app-control-context";

const inter = Inter({ subsets: ["latin"] });

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" sizes="32x32" />
        <link rel="icon" type="image/x-icon" href="./favicon.ico" />
        {/* <link
          rel="icon"
          href="/icon?<generated>"
          type="image/<generated>"
          sizes="<generated>"
        />
        <link
          rel="apple-touch-icon"
          href="/apple-icon?<generated>"
          type="image/<generated>"
          sizes="<generated>"
        /> */}
        <meta name="apple-touch-fullscreen" content="yes" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black" />
      </head>

      <AllowSound>
        <PeerProvider>
          <SpessasynthProvider>
            <AppControlProvider>
              <body className={`${inter.className} p-2.5 bg-slate-500 `}>
                <div className="fixed w-screen h-screen top-0 left-0 -z-20  bg-[url('/wallpaper-2.jpeg')] bg-cover bg-center opacity-50"></div>
                {children}
              </body>
            </AppControlProvider>
          </SpessasynthProvider>
        </PeerProvider>
      </AllowSound>
    </html>
  );
}
