import type { Metadata, Viewport } from "next";
import { Inter, Noto_Sans_Thai_Looped } from "next/font/google";
import "../globals.css";
import { SpessasynthProvider } from "../../context/spessasynth-context";
import AllowSound from "@/components/tools/allow-sound";

import { PeerProvider } from "../../context/remote-context";
import { AppControlProvider } from "@/context/app-control-context";
import { PlayerProvider } from "@/context/player-context";

const inter = Noto_Sans_Thai_Looped({
  weight: "400",
  subsets: ["latin", "thai", "latin-ext"],
});

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export const metadata: Metadata = {
  title: "Karaoke Online",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/icon.ico" sizes="48x48" />
        <link rel="icon" type="image/x-icon" href="./icon.ico" />
        <link
          rel="icon"
          href="/icon?<generated>"
          type="image/<generated>"
          sizes="<generated>"
        />
        <link
          rel="apple-touch-icon"
          href="/apple-icon?<generated>"
          type="image/<generated>"
          sizes="<generated>"
        />
        <meta name="apple-touch-fullscreen" content="yes" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black" />
      </head>

      <body className={`relative ${inter.className} p-2.5 bg-slate-500 `}>
        <div className="fixed w-screen h-screen top-0 left-0 -z-20  bg-[url('/wallpaper-3.png')] bg-cover bg-center  "></div>
        <AllowSound>
          <PeerProvider>
            <SpessasynthProvider>
              <AppControlProvider>
                <PlayerProvider>{children}</PlayerProvider>
              </AppControlProvider>
            </SpessasynthProvider>
          </PeerProvider>
        </AllowSound>
      </body>
    </html>
  );
}
