import { Viewport, Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { MixerProvider } from "@/context/mixer-context";
import { PeerProvider } from "@/context/remote-context";
const inter = Inter({ subsets: ["latin"] });

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <PeerProvider>
        <MixerProvider>
          <body>{children}</body>
        </MixerProvider>
      </PeerProvider>
    </html>
  );
}
